name: eikyusho_extensions
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  # * Core
  flutter:
    sdk: flutter

  image: ^4.2.0 # ? Image processing
  path: ^1.9.0  # ? File system
  xml: ^6.5.0 # ? XML parsing

  # * Dev Utility
  meta: ^1.12.0 # ? Class annotations

dev_dependencies:
  # * Utility
  very_good_analysis: ^5.1.0 # ? For linting